"""auth stack initial

Revision ID: 557f2e586456
Revises: 
Create Date: 2026-07-30 19:25:17.086284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '557f2e586456'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_audit_logs',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('user_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_hash', sa.String(length=128), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_index('ix_auth_audit_action_ts', 'auth_audit_logs', ['action', 'ts'], unique=False)
    op.create_index(op.f('ix_auth_audit_logs_action'), 'auth_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_auth_audit_logs_id'), 'auth_audit_logs', ['id'], unique=True)
    op.create_index(op.f('ix_auth_audit_logs_ts'), 'auth_audit_logs', ['ts'], unique=False)
    op.create_index(op.f('ix_auth_audit_logs_user_id'), 'auth_audit_logs', ['user_id'], unique=False)
    op.create_table('auth_oauth_states',
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_index(op.f('ix_auth_oauth_states_expires_at'), 'auth_oauth_states', ['expires_at'], unique=False)
    op.create_table('auth_password_reset_attempts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pra_email_ts', 'auth_password_reset_attempts', ['email_hash', 'ts'], unique=False)
    op.create_index('ix_pra_ip_ts', 'auth_password_reset_attempts', ['ip', 'ts'], unique=False)
    op.create_index('ix_pra_ts', 'auth_password_reset_attempts', ['ts'], unique=False)
    op.create_table('auth_security_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_security_events_audit_id'), 'auth_security_events', ['audit_id'], unique=False)
    op.create_index(op.f('ix_auth_security_events_user_id'), 'auth_security_events', ['user_id'], unique=False)
    op.create_table('auth_users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=512), nullable=True),
    sa.Column('mfa_bypass', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('auth_provider', sa.String(length=32), nullable=True),
    sa.Column('picture_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_table('auth_clients',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('intake_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_clients_email'), 'auth_clients', ['email'], unique=False)
    op.create_index(op.f('ix_auth_clients_user_id'), 'auth_clients', ['user_id'], unique=False)
    op.create_table('auth_login_continuations',
    sa.Column('ticket_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mfa_satisfied_now', sa.Boolean(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_auth_login_continuations_expires_at'), 'auth_login_continuations', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_login_continuations_user_id'), 'auth_login_continuations', ['user_id'], unique=False)
    op.create_table('auth_login_history',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_login_history_email_hash'), 'auth_login_history', ['email_hash'], unique=False)
    op.create_index('ix_auth_login_history_email_ts', 'auth_login_history', ['email_hash', 'ts'], unique=False)
    op.create_index(op.f('ix_auth_login_history_ts'), 'auth_login_history', ['ts'], unique=False)
    op.create_index(op.f('ix_auth_login_history_user_id'), 'auth_login_history', ['user_id'], unique=False)
    op.create_table('auth_oauth_handoffs',
    sa.Column('handoff_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('access_token', sa.String(length=4096), nullable=False),
    sa.Column('refresh_cookie_value', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('handoff_id')
    )
    op.create_index(op.f('ix_auth_oauth_handoffs_user_id'), 'auth_oauth_handoffs', ['user_id'], unique=False)
    op.create_table('auth_password_reset_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_ip', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_password_reset_tokens_expires_at'), 'auth_password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_password_reset_tokens_token_hash'), 'auth_password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_password_reset_tokens_user_id'), 'auth_password_reset_tokens', ['user_id'], unique=False)
    op.create_table('auth_user_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idle_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=64), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('ip_first', sa.String(length=64), nullable=True),
    sa.Column('ip_last', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('mfa_satisfied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('family_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_sessions_absolute_expires_at'), 'auth_user_sessions', ['absolute_expires_at'], unique=False)
    op.create_index(op.f('ix_auth_user_sessions_family_id'), 'auth_user_sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_auth_user_sessions_revoked_at'), 'auth_user_sessions', ['revoked_at'], unique=False)
    op.create_index('ix_auth_user_sessions_user_active', 'auth_user_sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_auth_user_sessions_user_id'), 'auth_user_sessions', ['user_id'], unique=False)
    op.create_table('auth_refresh_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('parent_token_id', sa.String(length=64), nullable=True),
    sa.Column('replaced_by_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=64), nullable=True),
    sa.Column('ip_created', sa.String(length=64), nullable=True),
    sa.Column('ip_last_used', sa.String(length=64), nullable=True),
    sa.Column('user_agent_created', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['auth_user_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_refresh_tokens_expires_at'), 'auth_refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_auth_refresh_tokens_family_active', 'auth_refresh_tokens', ['family_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_auth_refresh_tokens_family_id'), 'auth_refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_auth_refresh_tokens_revoked_at'), 'auth_refresh_tokens', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_auth_refresh_tokens_session_id'), 'auth_refresh_tokens', ['session_id'], unique=False)
    op.create_index(op.f('ix_auth_refresh_tokens_token_hash'), 'auth_refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_refresh_tokens_user_id'), 'auth_refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_refresh_tokens_user_id'), table_name='auth_refresh_tokens')
    op.drop_index(op.f('ix_auth_refresh_tokens_token_hash'), table_name='auth_refresh_tokens')
    op.drop_index(op.f('ix_auth_refresh_tokens_session_id'), table_name='auth_refresh_tokens')
    op.drop_index(op.f('ix_auth_refresh_tokens_revoked_at'), table_name='auth_refresh_tokens')
    op.drop_index(op.f('ix_auth_refresh_tokens_family_id'), table_name='auth_refresh_tokens')
    op.drop_index('ix_auth_refresh_tokens_family_active', table_name='auth_refresh_tokens')
    op.drop_index(op.f('ix_auth_refresh_tokens_expires_at'), table_name='auth_refresh_tokens')
    op.drop_table('auth_refresh_tokens')
    op.drop_index(op.f('ix_auth_user_sessions_user_id'), table_name='auth_user_sessions')
    op.drop_index('ix_auth_user_sessions_user_active', table_name='auth_user_sessions')
    op.drop_index(op.f('ix_auth_user_sessions_revoked_at'), table_name='auth_user_sessions')
    op.drop_index(op.f('ix_auth_user_sessions_family_id'), table_name='auth_user_sessions')
    op.drop_index(op.f('ix_auth_user_sessions_absolute_expires_at'), table_name='auth_user_sessions')
    op.drop_table('auth_user_sessions')
    op.drop_index(op.f('ix_auth_password_reset_tokens_user_id'), table_name='auth_password_reset_tokens')
    op.drop_index(op.f('ix_auth_password_reset_tokens_token_hash'), table_name='auth_password_reset_tokens')
    op.drop_index(op.f('ix_auth_password_reset_tokens_expires_at'), table_name='auth_password_reset_tokens')
    op.drop_table('auth_password_reset_tokens')
    op.drop_index(op.f('ix_auth_oauth_handoffs_user_id'), table_name='auth_oauth_handoffs')
    op.drop_table('auth_oauth_handoffs')
    op.drop_index(op.f('ix_auth_login_history_user_id'), table_name='auth_login_history')
    op.drop_index(op.f('ix_auth_login_history_ts'), table_name='auth_login_history')
    op.drop_index('ix_auth_login_history_email_ts', table_name='auth_login_history')
    op.drop_index(op.f('ix_auth_login_history_email_hash'), table_name='auth_login_history')
    op.drop_table('auth_login_history')
    op.drop_index(op.f('ix_auth_login_continuations_user_id'), table_name='auth_login_continuations')
    op.drop_index(op.f('ix_auth_login_continuations_expires_at'), table_name='auth_login_continuations')
    op.drop_table('auth_login_continuations')
    op.drop_index(op.f('ix_auth_clients_user_id'), table_name='auth_clients')
    op.drop_index(op.f('ix_auth_clients_email'), table_name='auth_clients')
    op.drop_table('auth_clients')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_table('auth_users')
    op.drop_index(op.f('ix_auth_security_events_user_id'), table_name='auth_security_events')
    op.drop_index(op.f('ix_auth_security_events_audit_id'), table_name='auth_security_events')
    op.drop_table('auth_security_events')
    op.drop_index('ix_pra_ts', table_name='auth_password_reset_attempts')
    op.drop_index('ix_pra_ip_ts', table_name='auth_password_reset_attempts')
    op.drop_index('ix_pra_email_ts', table_name='auth_password_reset_attempts')
    op.drop_table('auth_password_reset_attempts')
    op.drop_index(op.f('ix_auth_oauth_states_expires_at'), table_name='auth_oauth_states')
    op.drop_table('auth_oauth_states')
    op.drop_index(op.f('ix_auth_audit_logs_user_id'), table_name='auth_audit_logs')
    op.drop_index(op.f('ix_auth_audit_logs_ts'), table_name='auth_audit_logs')
    op.drop_index(op.f('ix_auth_audit_logs_id'), table_name='auth_audit_logs')
    op.drop_index(op.f('ix_auth_audit_logs_action'), table_name='auth_audit_logs')
    op.drop_index('ix_auth_audit_action_ts', table_name='auth_audit_logs')
    op.drop_table('auth_audit_logs')
    # ### end Alembic commands ###
