"""phase 3.3+3.4 clinical + messaging

Revision ID: 8ae0b2901822
Revises: c8f4a2e7b3d1
Create Date: 2026-07-31 14:54:35.091736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ae0b2901822'
down_revision: Union[str, Sequence[str], None] = 'c8f4a2e7b3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emr_form_templates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('legacy_mongo_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emr_live_soap_drafts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('appointment_id', sa.String(length=64), nullable=True),
    sa.Column('author_id', sa.String(length=64), nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emr_live_soap_drafts_appointment_id'), 'emr_live_soap_drafts', ['appointment_id'], unique=False)
    op.create_table('emr_soap_templates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('legacy_mongo_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emr_visit_chat',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('appointment_id', sa.String(length=64), nullable=True),
    sa.Column('sender_id', sa.String(length=64), nullable=True),
    sa.Column('sender_role', sa.String(length=32), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emr_visit_chat_appointment_id'), 'emr_visit_chat', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_emr_visit_chat_ts'), 'emr_visit_chat', ['ts'], unique=False)
    op.create_table('emr_push_subscriptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emr_push_subscriptions_user_id'), 'emr_push_subscriptions', ['user_id'], unique=False)
    op.create_table('emr_clinical_delegations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=True),
    sa.Column('delegate_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('scope', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=64), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('legacy_mongo_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['emr_clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['delegate_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emr_clinical_delegations_active'), 'emr_clinical_delegations', ['active'], unique=False)
    op.create_index(op.f('ix_emr_clinical_delegations_client_id'), 'emr_clinical_delegations', ['client_id'], unique=False)
    op.create_index(op.f('ix_emr_clinical_delegations_delegate_id'), 'emr_clinical_delegations', ['delegate_id'], unique=False)
    op.create_index(op.f('ix_emr_clinical_delegations_provider_id'), 'emr_clinical_delegations', ['provider_id'], unique=False)
    op.create_table('emr_form_submissions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=True),
    sa.Column('template_id', sa.String(length=64), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('legacy_mongo_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['emr_clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['emr_form_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emr_form_submissions_client_id'), 'emr_form_submissions', ['client_id'], unique=False)
    op.create_index(op.f('ix_emr_form_submissions_token'), 'emr_form_submissions', ['token'], unique=True)
    op.create_table('emr_lab_values',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('marker', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('reference_range', sa.String(length=120), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ordering_provider_id', sa.String(length=64), nullable=True),
    sa.Column('ordering_provider_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('legacy_mongo_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['emr_clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emr_lab_values_client_id'), 'emr_lab_values', ['client_id'], unique=False)
    op.create_table('emr_message_threads',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('practitioner_id', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('legacy_mongo_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['emr_clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['practitioner_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emr_message_threads_client_id'), 'emr_message_threads', ['client_id'], unique=False)
    op.create_index(op.f('ix_emr_message_threads_last_message_at'), 'emr_message_threads', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_emr_message_threads_practitioner_id'), 'emr_message_threads', ['practitioner_id'], unique=False)
    op.create_table('emr_treatment_plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('practitioner_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interventions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legacy_mongo_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['emr_clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['practitioner_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emr_treatment_plans_client_id'), 'emr_treatment_plans', ['client_id'], unique=False)
    op.create_table('emr_treatments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('created_by_name', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('legacy_mongo_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['emr_clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emr_treatments_client_id'), 'emr_treatments', ['client_id'], unique=False)
    op.create_table('emr_visit_notes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('practitioner_id', sa.String(length=64), nullable=True),
    sa.Column('practitioner_name', sa.String(length=200), nullable=True),
    sa.Column('drafted_by_id', sa.String(length=64), nullable=True),
    sa.Column('drafted_by_name', sa.String(length=200), nullable=True),
    sa.Column('drafted_by_role', sa.String(length=32), nullable=True),
    sa.Column('appointment_id', sa.String(length=64), nullable=True),
    sa.Column('subjective', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_by', sa.String(length=64), nullable=True),
    sa.Column('prev_hash', sa.String(length=128), nullable=True),
    sa.Column('note_hash', sa.String(length=128), nullable=True),
    sa.Column('amendments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prior_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('legacy_mongo_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['emr_clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['practitioner_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emr_visit_notes_appointment_id'), 'emr_visit_notes', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_emr_visit_notes_client_id'), 'emr_visit_notes', ['client_id'], unique=False)
    op.create_index(op.f('ix_emr_visit_notes_practitioner_id'), 'emr_visit_notes', ['practitioner_id'], unique=False)
    op.create_index(op.f('ix_emr_visit_notes_status'), 'emr_visit_notes', ['status'], unique=False)
    op.create_table('emr_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=True),
    sa.Column('sender_id', sa.String(length=64), nullable=True),
    sa.Column('sender_role', sa.String(length=32), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('legacy_mongo_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['emr_message_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emr_messages_created_at'), 'emr_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_emr_messages_thread_id'), 'emr_messages', ['thread_id'], unique=False)
    # ### end commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('emr_messages')
    op.drop_table('emr_visit_notes')
    op.drop_table('emr_treatments')
    op.drop_table('emr_treatment_plans')
    op.drop_table('emr_message_threads')
    op.drop_table('emr_lab_values')
    op.drop_table('emr_form_submissions')
    op.drop_table('emr_clinical_delegations')
    op.drop_table('emr_push_subscriptions')
    op.drop_table('emr_visit_chat')
    op.drop_table('emr_soap_templates')
    op.drop_table('emr_live_soap_drafts')
    op.drop_table('emr_form_templates')
